// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/404.tsx";
import * as $1 from "./routes/[name].tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/about.tsx";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/api/postData.ts";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/patttern.ts";
import * as $8 from "./routes/search.tsx";
import * as $9 from "./routes/store.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/PostTest.tsx";
import * as $$2 from "./islands/Redirect.tsx";
import * as $$3 from "./islands/Store.tsx";

const manifest = {
  routes: {
    "./routes/404.tsx": $0,
    "./routes/[name].tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/about.tsx": $3,
    "./routes/api/joke.ts": $4,
    "./routes/api/postData.ts": $5,
    "./routes/index.tsx": $6,
    "./routes/patttern.ts": $7,
    "./routes/search.tsx": $8,
    "./routes/store.tsx": $9,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/PostTest.tsx": $$1,
    "./islands/Redirect.tsx": $$2,
    "./islands/Store.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
